// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE03CY72ofth791aPDGccXMa_e48olAkY',
    appId: '1:341233678089:web:4a56ba4f8c0594254d85d8',
    messagingSenderId: '341233678089',
    projectId: 'notes-flutter-1725-sarth',
    authDomain: 'notes-flutter-1725-sarth.firebaseapp.com',
    storageBucket: 'notes-flutter-1725-sarth.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUetSM-eDKwbQ4eJzppe_H_41UyqC0Xh4',
    appId: '1:341233678089:ios:a6e03b75ef7354d54d85d8',
    messagingSenderId: '341233678089',
    projectId: 'notes-flutter-1725-sarth',
    storageBucket: 'notes-flutter-1725-sarth.appspot.com',
    iosBundleId: 'com.hello.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE03CY72ofth791aPDGccXMa_e48olAkY',
    appId: '1:341233678089:web:4d17551d7d52b3484d85d8',
    messagingSenderId: '341233678089',
    projectId: 'notes-flutter-1725-sarth',
    authDomain: 'notes-flutter-1725-sarth.firebaseapp.com',
    storageBucket: 'notes-flutter-1725-sarth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUetSM-eDKwbQ4eJzppe_H_41UyqC0Xh4',
    appId: '1:341233678089:ios:a6e03b75ef7354d54d85d8',
    messagingSenderId: '341233678089',
    projectId: 'notes-flutter-1725-sarth',
    storageBucket: 'notes-flutter-1725-sarth.appspot.com',
    iosBundleId: 'com.hello.notes',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD51FSBb-OL15KsxTzjRbWN6ktfXxa8PEE',
    appId: '1:341233678089:android:e446e3c148e604b34d85d8',
    messagingSenderId: '341233678089',
    projectId: 'notes-flutter-1725-sarth',
    storageBucket: 'notes-flutter-1725-sarth.appspot.com',
  );

}